### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by cmeesters** [galaxyproject/ansible-slurm#25]
Hi,

the last release is rather old. Particularly with the merges fixing issue #6 a new release would be merited, don't you think?

Best regards
Christian Meesters

**Comment by hexylena** [comment]
Hi @cmeesters the latest GitHub Release is quite old, but github releases != ansible releases.

The latest tag, 1.0.1 currently points at the latest commit of this repository, and you can find this tag on Ansible Galaxy. https://galaxy.ansible.com/galaxyproject/slurm

**Comment by hexylena** [comment]
I have deleted the other "releases", leaving only tags, to prevent future confusion.
